"use client";

import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { SurahDetail } from "@/services/quran";
import { useSettings } from "@/lib/SettingsContext";
import { useState } from "react";
import { createPortal } from "react-dom";

interface ExportPDFButtonProps {
  surah: SurahDetail;
}

export default function ExportPDFButton({ surah }: ExportPDFButtonProps) {
  const { showArabic, showLatin, showTranslation, script } = useSettings();
  const [isGenerating, setIsGenerating] = useState(false);

  // Hidden print container for high-fidelity export
  const renderPrintContent = () => (
    <div id="pdf-export-container" className="fixed top-0 left-0 -z-50 w-[210mm] bg-white text-black font-serif p-[20mm]">
      {/* Header */}
      <div className="text-center mb-10 border-b-2 pb-4" style={{ borderColor: '#064e3b' }}>
        <h1 className="text-4xl font-bold uppercase tracking-widest mb-2" style={{ color: '#064e3b' }}>{surah.namaLatin}</h1>
        <p className="text-sm font-serif uppercase tracking-widest" style={{ color: '#4b5563' }}>{surah.arti} • {surah.jumlahAyat} VERSES</p>
      </div>

      {/* Bismillah */}
      {surah.nomor !== 1 && surah.nomor !== 9 && (
        <div className="flex justify-center mb-8">
             <p className="text-3xl quran-indo leading-relaxed font-bold" style={{ color: '#000000' }}>
               بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
             </p>
        </div>
      )}

      {/* Verses */}
      <div className="space-y-6">
        {surah.ayat.map((ayat, index) => (
          <div key={ayat.nomorAyat} className="border-b pb-6 break-inside-avoid" style={{ borderColor: '#e5e7eb' }}>
             <div className="flex items-start justify-between gap-6 mb-4">
               {/* Number Badge */}
               <div className="w-8 h-8 rounded-full border-2 flex items-center justify-center text-xs font-bold shrink-0" style={{ borderColor: '#064e3b', color: '#064e3b' }}>
                 {ayat.nomorAyat}
               </div>

               {/* Arabic Text */}
               {showArabic && (
                 <p className={`text-right w-full text-3xl quran-indo leading-loose dir-rtl ${script === 'madinah' ? 'font-madinah' : 'font-lpmq'}`} style={{ color: '#000000' }}>
                   {ayat.teksArab}
                 </p>
               )}
             </div>

             {/* Latin & Translation */}
             {(showLatin || showTranslation) && (
               <div className="pl-14 space-y-2">
                 {showLatin && (
                   <p className="text-sm italic font-serif font-medium" style={{ color: '#065f46' }}>
                     {ayat.teksLatin}
                   </p>
                 )}
                 {showTranslation && (
                   <p className="text-sm font-serif leading-relaxed text-justify" style={{ color: '#1f2937' }}>
                     {ayat.teksIndonesia || ayat.teksEnglish}
                   </p>
                 )}
               </div>
             )}
          </div>
        ))}
      </div>
      
      {/* Footer */}
      <div className="mt-12 text-center text-xs border-t pt-4" style={{ color: '#9ca3af', borderColor: '#e5e7eb' }}>
        Generated by Quran Horizon | Premium Digital Mushaf
      </div>
    </div>
  );

  const generatePDF = async () => {
    setIsGenerating(true);
    
    // Check if fonts are loaded before capturing
    await document.fonts.ready;

    const element = document.getElementById("pdf-export-container");
    if (!element) return;

    try {
      // Use html2canvas to capture the hidden container as an image
      const canvas = await html2canvas(element, {
        scale: 2, // High resolution
        useCORS: true, 
        logging: false,
        backgroundColor: "#ffffff"
      });

      const imgData = canvas.toDataURL("image/jpeg", 0.9);
      const pdf = new jsPDF("p", "mm", "a4");
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      
      const imgWidth = pdfWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      let heightLeft = imgHeight;
      let position = 0;

      // Add first page
      pdf.addImage(imgData, "JPEG", 0, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight;

      // Add subsequent pages if content overflows
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, "JPEG", 0, position, imgWidth, imgHeight);
        heightLeft -= pdfHeight;
      }

      pdf.save(`QuranHorizon_${surah.namaLatin}.pdf`);
    } catch (error) {
      console.error("PDF Generation failed:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <>
      <button
        onClick={generatePDF}
        disabled={isGenerating}
        title="Generate PDF Book"
        className="group relative flex h-10 w-10 sm:w-auto items-center justify-center sm:gap-2 overflow-hidden rounded-xl bg-emerald-deep text-white shadow-[0_10px_20px_rgba(6,78,59,0.2)] transition-all hover:translate-y-[-2px] hover:shadow-[0_15px_30px_rgba(6,78,59,0.3)] active:scale-95 sm:px-4 disabled:opacity-70 disabled:cursor-wait"
      >
        <div className="absolute inset-0 bg-gradient-to-tr from-emerald-900 via-emerald-700 to-emerald-500 opacity-0 group-hover:opacity-100 transition-opacity"></div>
        <div className="relative z-10 flex items-center gap-2">
          {isGenerating ? (
             <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
               <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
               <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
             </svg>
          ) : (
            <svg className="h-4 w-4 transform group-hover:rotate-[-10deg] transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          )}
          <span className="hidden sm:inline uppercase tracking-[0.2em] text-[10px] font-black">{isGenerating ? "GENERATING..." : "EXPORT PDF"}</span>
        </div>
      </button>

      {/* Render the hidden print content into the DOM */}
      {createPortal(renderPrintContent(), document.body)}
    </>
  );
}
